### PR TITLE
added network handling for eula and privacy policy

### PR DESCRIPTION
**Pull request by schenkty**
Not sure why all the assets are included in the commit, its annoying and nothing was changed for them but anyway this will now check if it can load nanowalletcompany.com and if it can't, it will load the local html file from its bundle

### CODE REVIEW

**Comment by zackshapiro** [comment]
Maybe try the Reachability pod rather than Alamofire? I think we can get the same functionality without the heft of AF

**Comment by schenkty** [comment]
No worries, working on it now.

**Comment by schenkty** [comment]
well, again Xcode decided to add extra files to commit but anyhow, I rewrote the class to use built-in frameworks instead of a pod. Reachability didn't work properly so I figured it was best to just not base it on anything. let me know your thoughts

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.

**Pull request closed without merging**
